In [86]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt

In [60]:
data = pd.read_csv('Iris.csv')
data.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [61]:
data["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [62]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
# data["Species"].value_counts()

In [63]:
embarked_dict = {"Iris-setosa": 3, "Iris-versicolor": 2, "Iris-virginica": 1}
data["Species"].replace(embarked_dict, inplace=True)
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        3
1   2            4.9           3.0            1.4           0.2        3
2   3            4.7           3.2            1.3           0.2        3
3   4            4.6           3.1            1.5           0.2        3
4   5            5.0           3.6            1.4           0.2        3

In [75]:
X = data[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
Y = data["Species"]

In [76]:
X = X.to_numpy()
Y = Y.to_numpy()

In [77]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [78]:
nb = GaussianNB()
nb.fit(X_train, Y_train)
print(nb.score(X_train, Y_train))

0.975


In [85]:
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, Y_train)
# nb_classifier = GaussianNB()
y_pred = nb_classifier.predict(X_test)

In [88]:
acc_score = accuracy_score(Y_test, y_pred)
conf_mat = confusion_matrix(
        Y_test, y_pred)

print(acc_score)
print(conf_mat)

0.9
[[ 8  0  0]
 [ 3  9  0]
 [ 0  0 10]]


In [89]:
precision, recall, fscore, _ = sklearn.metrics.precision_recall_fscore_support(Y_test, y_pred)

In [93]:
print(f'Precision(1): {precision[0]} \n Recall(1): {recall[0]} \n Fscore(1): {fscore[0]}\n\n')
print(f'Precision(2): {precision[1]} \n Recall(2): {recall[1]} \n Fscore(2): {fscore[1]}\n\n')
print(f'Precision(3): {precision[2]} \n Recall(3): {recall[2]} \n Fscore(3): {fscore[2]}\n\n')
# print(precision)

Precision(1): 0.7272727272727273 
 Recall(1): 1.0 
 Fscore(1): 0.8421052631578948


Precision(2): 1.0 
 Recall(2): 0.75 
 Fscore(2): 0.8571428571428571


Precision(3): 1.0 
 Recall(3): 1.0 
 Fscore(3): 1.0




In [94]:
LogReg = LogisticRegression(max_iter=10000)
LogReg.fit(X_train,Y_train)
print(LogReg.score(X_train, Y_train))

0.975


In [96]:
yLR_pred = LogReg.predict(X_test)

In [97]:
precision, recall, fscore, _ = sklearn.metrics.precision_recall_fscore_support(Y_test, yLR_pred)

In [99]:
print(f'Precision(1): {precision[0]} \n Recall(1): {recall[0]} \n Fscore(1): {fscore[0]}\n\n')
print(f'Precision(2): {precision[1]} \n Recall(2): {recall[1]} \n Fscore(2): {fscore[1]}\n\n')
print(f'Precision(3): {precision[2]} \n Recall(3): {recall[2]} \n Fscore(3): {fscore[2]}\n\n')

Precision(1): 1.0 
 Recall(1): 0.75 
 Fscore(1): 0.8571428571428571


Precision(2): 0.8571428571428571 
 Recall(2): 1.0 
 Fscore(2): 0.923076923076923


Precision(3): 1.0 
 Recall(3): 1.0 
 Fscore(3): 1.0


